### ISSUE TITLE
Can't switch to librecoopd3xp (Linux, Manjero)

### ISSUE THREAD

**Issue by Rhiyo** [Stradex/librecoop#37]
I switched the pk4 files to the ones from Alpha 1.1 and it worked, just doesn't work with the pk4 files in 1.2 for me.

Normal librecoop works, but for the expansion I just get a blackscreen, cursor and no menu. The terminal gives me a lot of warnings related to guis/mainmenu.gui

> WARNING: Window AnimSystemToGame in gui guis/mainmenu.gui: a transition does not have a valid destination var OptionsBgMain11::rect

for example.

**Comment by Stradex** [comment]
I think I know what happened. You are trying to load librecoopd3xp from the mods tab at the main menu. That's not ideal (I should clarify that). You need to create a batch file or something to open dhewm3 with the following commands

dhewm3 +set fs_game_base d3xp +set fs_game librecoopd3xp

And with THAT method it should work properly.

**Comment by Rhiyo** [comment]
That worked, thankyou. Were there are instructions to do this somewhere? Or would most people just know how to do this based on being used to playing with doom mods?
